// Generated by AI (UnitTest MCP)
// Extended as a pre-migration behavior baseline — see
// docs/features/personas-fetch-baseline-pre-react-query.md. These tests must
// pass against BOTH the current module-cache implementation and whatever
// React Query implementation eventually replaces it; if one needs to change
// to keep passing, that's a behavior change to call out explicitly, not a
// silent side effect of the migration.
import { beforeEach, describe, expect, it, vi } from 'vitest'

const { apiFetchJson } = vi.hoisted(() => ({ apiFetchJson: vi.fn() }))

vi.mock('./client', async importOriginal => {
  const actual = await importOriginal<typeof import('./client')>()
  return { ...actual, apiFetchJson }
})

import { bustPersonasCache, fetchPersonas } from './personas'

// Shared fixture factory so every test isn't repeating the full backend shape.
function makeRepo(overrides: Record<string, unknown> = {}) {
  return {
    id: 'repo-1',
    name: 'Sales Agent',
    is_active: true,
    active_version_id: 'version-1',
    active_version: {
      id: 'version-1',
      persona_repo_id: 'repo-1',
      name: 'Sales Agent',
      handler: 'sales_agent',
      prompt: 'Help with sales',
      description: 'Sales helper',
      is_active: true,
      model_id: null,
      image_url: null,
      image_s3_key: null,
      temperature: null,
      documents: [],
      links: [],
      connectors: [],
      blocked_connectors: [],
      source_share_id: null,
      version_tags: [],
      persona_tags: ['sales'],
      created_at: '2026-06-18T00:00:00Z',
      updated_at: '2026-06-18T00:00:00Z',
    },
    published_version_id: 'version-1',
    published_version: null,
    published_at: '2026-06-18T00:00:00Z',
    is_published: true,
    visibility: 'org',
    organization_id: 'org-1',
    version_count: 1,
    created_at: '2026-06-18T00:00:00Z',
    updated_at: '2026-06-18T00:00:00Z',
    ...overrides,
  }
}

describe('fetchPersonas', () => {
  beforeEach(() => {
    apiFetchJson.mockReset()
    bustPersonasCache()
  })

  it('preserves repo visibility and the live version connector slugs', async () => {
    const repo = makeRepo()
    repo.active_version.connectors = ['slack', 'gmail']
    apiFetchJson.mockResolvedValueOnce([repo])

    await expect(fetchPersonas()).resolves.toMatchObject([{
      id: 'repo-1',
      visibility: 'team',
      connectorSlugs: ['slack', 'gmail'],
    }])
  })

  it('returns an empty array when the org has no personas, without throwing', async () => {
    apiFetchJson.mockResolvedValueOnce([])
    await expect(fetchPersonas()).resolves.toEqual([])
  })

  it('dedupes concurrent calls into a single network request (in-flight dedupe)', async () => {
    let resolveList!: (value: unknown[]) => void
    const pending = new Promise(resolve => { resolveList = resolve })
    apiFetchJson.mockReturnValueOnce(pending)

    const call1 = fetchPersonas()
    const call2 = fetchPersonas()
    resolveList([])
    const [result1, result2] = await Promise.all([call1, call2])

    expect(apiFetchJson).toHaveBeenCalledTimes(1)
    expect(result1).toEqual(result2)
  })

  it('serves cached data within the TTL window without a second network call', async () => {
    apiFetchJson.mockResolvedValueOnce([])
    await fetchPersonas()
    await fetchPersonas()
    expect(apiFetchJson).toHaveBeenCalledTimes(1)
  })

  it('fetches the list and nothing else — no per-persona detail requests', async () => {
    apiFetchJson.mockResolvedValueOnce([makeRepo({ visibility: 'org' }), makeRepo({ id: 'repo-2' })])

    const result = await fetchPersonas()
    expect(result).toHaveLength(2)
    expect(apiFetchJson).toHaveBeenCalledTimes(1)
  })

  it('rejects a response that does not match the backend schema', async () => {
    apiFetchJson.mockResolvedValueOnce([{ id: 'repo-1', name: 'Sales Agent' }])
    await expect(fetchPersonas()).rejects.toThrow()
  })

  it('bustPersonasCache forces the next fetchPersonas call back to the network', async () => {
    apiFetchJson.mockResolvedValueOnce([]).mockResolvedValueOnce([])
    await fetchPersonas()
    bustPersonasCache()
    await fetchPersonas()
    expect(apiFetchJson).toHaveBeenCalledTimes(2)
  })

  // This suite runs in vitest's "node" environment (see vitest.config.ts —
  // deliberate, tests target pure logic, no DOM) so `window` is undefined here,
  // same as any SSR context. bustPersonasCache()'s event dispatch is guarded by
  // `typeof window !== 'undefined'` specifically so it's safe to call from a
  // non-browser context — this test protects that guard, not the browser-only
  // fan-out to teams.ts's owner-map cache (which needs a jsdom environment to
  // exercise for real and is out of scope for this pure-logic suite).
  it('bustPersonasCache does not throw when window is undefined (SSR-safe)', () => {
    expect(typeof window).toBe('undefined')
    expect(() => bustPersonasCache()).not.toThrow()
  })
})
