// Generated by AI (UnitTest MCP)
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { resolveSelectableChatPersonas } from './chat-personas'
import type { Persona, PersonaRepoResponse } from './api/personas'

function persona(overrides: Partial<Persona>): Persona {
  return {
    id: 'persona',
    name: 'Agent',
    handle: '@agent',
    description: '',
    imageUrl: null,
    modelId: null,
    tags: [],
    temperature: null,
    isActive: true,
    isPaused: false,
    status: 'active',
    activeVersionId: 'version',
    workingVersionId: 'version',
    publishedAt: null,
    versionCount: 1,
    visibility: 'private',
    hasSystemInstructions: true,
    sourceShareId: null,
    createdAt: '',
    updatedAt: '',
    ...overrides,
  }
}

describe('resolveSelectableChatPersonas', () => {
  it('keeps every visible agent regardless of team and copies non-owned shared agents', async () => {
    const copyPersona = vi.fn().mockResolvedValue({
      id: 'copied-other-team',
      published_version_id: 'copied-version',
      published_version: null,
      active_version: null,
    } as PersonaRepoResponse)

    const result = await resolveSelectableChatPersonas([
      persona({ id: 'private', name: 'Private agent' }),
      persona({ id: 'owned-team', name: 'Owned team agent', visibility: 'team' }),
      persona({ id: 'other-team', name: 'Other team agent', visibility: 'team' }),
    ], {
      'owned-team': 'viewer',
      'other-team': 'another-user',
    }, 'viewer', false, copyPersona)

    expect(result.map(agent => agent.name)).toEqual([
      'Private agent',
      'Owned team agent',
      'Other team agent',
    ])
    expect(result[2]?.id).toBe('copied-other-team')
    expect(copyPersona).toHaveBeenCalledOnce()
    expect(copyPersona).toHaveBeenCalledWith('other-team', 'version')
  })

  it('drops a non-owned agent entirely when its copy fails, instead of falling back to the original (unowned) version id', async () => {
    // A version id that belongs to someone else is rejected by chat send
    // (backend: persona.user_id !== caller -> 404 "Persona not found"), so a
    // failed clone must never be surfaced as a selectable/attachable agent.
    // Distinct persona id from the test above — copiedPersonaCache is a
    // module-level cache keyed by persona id, so reusing 'other-team' would
    // return that test's already-cached successful clone instead of ever
    // calling this test's (rejecting) copyPersona mock.
    const copyPersona = vi.fn().mockRejectedValue(new Error('use failed'))

    const result = await resolveSelectableChatPersonas([
      persona({ id: 'private', name: 'Private agent' }),
      persona({ id: 'other-team-failing', name: 'Other team agent (broken copy)', visibility: 'team' }),
    ], {
      'other-team-failing': 'another-user',
    }, 'viewer', false, copyPersona)

    expect(result.map(agent => agent.name)).toEqual(['Private agent'])
  })
})

const { fetchPersonasMock } = vi.hoisted(() => ({
  fetchPersonasMock: vi.fn(),
}))

vi.mock('@/lib/api/personas', async (importOriginal) => {
  const actual = await importOriginal<typeof import('@/lib/api/personas')>()
  return { ...actual, fetchPersonas: fetchPersonasMock }
})

describe('fetchSelectableChatPersonas', () => {
  beforeEach(() => {
    fetchPersonasMock.mockReset()
  })

  it('excludes draft agents — they are not published/usable yet', async () => {
    const { fetchSelectableChatPersonas } = await import('./chat-personas')
    fetchPersonasMock.mockResolvedValue([
      persona({ id: 'live', name: 'Live agent', status: 'active' }),
      persona({ id: 'wip', name: 'Draft agent', status: 'draft' }),
    ])

    const result = await fetchSelectableChatPersonas('org-1', 'viewer', false)

    expect(result.map(agent => agent.name)).toEqual(['Live agent'])
  })
})
