// Generated by AI (UnitTest MCP)
import { describe, expect, it, vi } from 'vitest'
import { resolveSelectableChatPersonas } from './chat-personas'
import type { Persona, PersonaRepoResponse } from './api/personas'

function persona(overrides: Partial<Persona>): Persona {
  return {
    id: 'persona',
    name: 'Agent',
    handle: '@agent',
    description: '',
    imageUrl: null,
    modelId: null,
    tags: [],
    temperature: null,
    isActive: true,
    isPaused: false,
    status: 'active',
    activeVersionId: 'version',
    workingVersionId: 'version',
    publishedAt: null,
    versionCount: 1,
    visibility: 'private',
    teamIds: [],
    hasSystemInstructions: true,
    sourceShareId: null,
    createdAt: '',
    updatedAt: '',
    ...overrides,
  }
}

describe('resolveSelectableChatPersonas', () => {
  it('keeps every visible agent regardless of team and copies non-owned shared agents', async () => {
    const copyPersona = vi.fn().mockResolvedValue({
      id: 'copied-other-team',
      published_version_id: 'copied-version',
      published_version: null,
      active_version: null,
    } as PersonaRepoResponse)

    const result = await resolveSelectableChatPersonas([
      persona({ id: 'private', name: 'Private agent' }),
      persona({ id: 'owned-team', name: 'Owned team agent', visibility: 'team', teamIds: ['team-1'] }),
      persona({ id: 'other-team', name: 'Other team agent', visibility: 'team', teamIds: ['team-2'] }),
    ], {
      'owned-team': 'viewer',
      'other-team': 'another-user',
    }, 'viewer', false, copyPersona)

    expect(result.map(agent => agent.name)).toEqual([
      'Private agent',
      'Owned team agent',
      'Other team agent',
    ])
    expect(result[2]?.id).toBe('copied-other-team')
    expect(copyPersona).toHaveBeenCalledOnce()
    expect(copyPersona).toHaveBeenCalledWith('other-team', 'version')
  })
})
