// Local brand-logo assets for connectors, keyed by slug. The backend does NOT
// return logo URLs (`/connectors` leaves `icon_url` null), so the FE bundles
// these under /public/connector-logos/ and resolves them by slug. Keep the
// slug variants (dash / underscore / concatenated) in sync with the backend's
// connector slugs.
export const CONNECTOR_LOGO_MAP: Record<string, string> = {
  'airtable':          '/connector-logos/airtable.svg',
  'asana':             '/connector-logos/asana.svg',
  'calendly':          '/connector-logos/calendly.svg',
  'clickup':           '/connector-logos/clickup.svg',
  'click-up':          '/connector-logos/clickup.svg',
  'fireflies':         '/connector-logos/fireflies.svg',
  'fireflies-ai':      '/connector-logos/fireflies.svg',
  'gmail':             '/connector-logos/gmail.svg',
  'googleads':         '/connector-logos/google-ads.svg',
  'google-ads':        '/connector-logos/google-ads.svg',
  'google_ads':        '/connector-logos/google-ads.svg',
  'googleanalytics':   '/connector-logos/google-analytics.svg',
  'google-analytics':  '/connector-logos/google-analytics.svg',
  'google_analytics':  '/connector-logos/google-analytics.svg',
  'googlecalendar':    '/connector-logos/google-calendar.svg',
  'google-calendar':   '/connector-logos/google-calendar.svg',
  'google_calendar':   '/connector-logos/google-calendar.svg',
  'googledocs':        '/connector-logos/google-docs.svg',
  'google-docs':       '/connector-logos/google-docs.svg',
  'google_docs':       '/connector-logos/google-docs.svg',
  'googledrive':       '/connector-logos/google-drive.svg',
  'google-drive':      '/connector-logos/google-drive.svg',
  'google_drive':      '/connector-logos/google-drive.svg',
  'googlesheets':      '/connector-logos/google-sheets.svg',
  'google-sheets':     '/connector-logos/google-sheets.svg',
  'google_sheets':     '/connector-logos/google-sheets.svg',
  'hubspot':           '/connector-logos/hubspot.svg',
  'jira':              '/connector-logos/jira.svg',
  'linear':            '/connector-logos/linear.svg',
  'linkedin':          '/connector-logos/linkedin.svg',
  'meta':              '/connector-logos/meta.svg',
  'meta-ads':          '/connector-logos/meta.svg',
  'meta_ads':          '/connector-logos/meta.svg',
  'metaads':           '/connector-logos/meta.svg',
  'facebook':          '/connector-logos/meta.svg',
  'facebook-ads':      '/connector-logos/meta.svg',
  'facebook_ads':      '/connector-logos/meta.svg',
  'facebookads':       '/connector-logos/meta.svg',
  'notion':            '/connector-logos/notion.svg',
  'outlook':           '/connector-logos/outlook.svg',
  'microsoft-outlook': '/connector-logos/outlook.svg',
  'salesforce':        '/connector-logos/salesforce.svg',
  'klaviyo':           '/connector-logos/klaviyo.svg',
  'shipengine':        '/connector-logos/shipengine.jpeg',
  'ship-engine':       '/connector-logos/shipengine.jpeg',
  'shipstation':       '/connector-logos/ship-station.png',
  'ship-station':      '/connector-logos/ship-station.png',
  'ship_station':      '/connector-logos/ship-station.png',
  'shopify':           '/connector-logos/shopify.svg',
  'slack':             '/connector-logos/slack.svg',
  'stripe':            '/connector-logos/stripe.svg',
  'zoom':              '/connector-logos/zoom.svg',
  'beehiiv':           '/connector-logos/beehiiv.svg',
  'booking-com':       '/connector-logos/booking-com.svg',
  'bookingcom':        '/connector-logos/booking-com.svg',
  'canva':             '/connector-logos/canva.svg',
  'customer-io':       '/connector-logos/customer-io.svg',
  'customerio':        '/connector-logos/customer-io.svg',
  'customer_io':       '/connector-logos/customer-io.svg',
  'databricks':        '/connector-logos/databricks.svg',
  'figma':             '/connector-logos/figma.svg',
  'intercom':          '/connector-logos/intercom.svg',
  'miro':              '/connector-logos/miro.svg',
  'mixpanel':          '/connector-logos/mixpanel.svg',
  'supabase':          '/connector-logos/supabase.svg',
  'triple-whale':      '/connector-logos/triple_whale.svg',
  'triplewhale':       '/connector-logos/triple_whale.svg',
  'triple_whale':      '/connector-logos/triple_whale.svg',
  'vercel':            '/connector-logos/vercel.svg',
  'whatsapp':          '/connector-logos/whatsapp.svg',
  'amplitude':         '/connector-logos/amplitude.svg',
  'attio':             '/connector-logos/attio.svg',
  'box':               '/connector-logos/box.svg',
  'fathom':            '/connector-logos/fathom.svg',
  'granola':           '/connector-logos/granola.svg',
  'granola-ai':        '/connector-logos/granola.svg',
  'microsoft-bookings':    '/connector-logos/microsoft-bookings.svg',
  'microsoftbookings':     '/connector-logos/microsoft-bookings.svg',
  'microsoft_bookings':    '/connector-logos/microsoft-bookings.svg',
  'bookings':              '/connector-logos/microsoft-bookings.svg',
  'microsoft-clarity':     '/connector-logos/microsoft-clarity.png',
  'microsoftclarity':      '/connector-logos/microsoft-clarity.png',
  'microsoft_clarity':     '/connector-logos/microsoft-clarity.png',
  'clarity':               '/connector-logos/microsoft-clarity.png',
  'microsoft-excel':       '/connector-logos/microsoft-excel.svg',
  'microsoftexcel':        '/connector-logos/microsoft-excel.svg',
  'microsoft_excel':       '/connector-logos/microsoft-excel.svg',
  'excel':                 '/connector-logos/microsoft-excel.svg',
  'microsoft-onedrive':    '/connector-logos/microsoft-onedrive.svg',
  'microsoftonedrive':     '/connector-logos/microsoft-onedrive.svg',
  'microsoft_onedrive':    '/connector-logos/microsoft-onedrive.svg',
  'onedrive':              '/connector-logos/microsoft-onedrive.svg',
  'microsoft-onenote':     '/connector-logos/microsoft-onenote.svg',
  'microsoftonenote':      '/connector-logos/microsoft-onenote.svg',
  'microsoft_onenote':     '/connector-logos/microsoft-onenote.svg',
  'onenote':               '/connector-logos/microsoft-onenote.svg',
  'microsoft-planner':     '/connector-logos/microsoft-planner.svg',
  'microsoftplanner':      '/connector-logos/microsoft-planner.svg',
  'microsoft_planner':     '/connector-logos/microsoft-planner.svg',
  'planner':               '/connector-logos/microsoft-planner.svg',
  'microsoft-powerpoint':  '/connector-logos/microsoft-powerpoint.svg',
  'microsoftpowerpoint':   '/connector-logos/microsoft-powerpoint.svg',
  'microsoft_powerpoint':  '/connector-logos/microsoft-powerpoint.svg',
  'powerpoint':            '/connector-logos/microsoft-powerpoint.svg',
  'microsoft-sharepoint':  '/connector-logos/microsoft-sharepoint.svg',
  'microsoftsharepoint':   '/connector-logos/microsoft-sharepoint.svg',
  'microsoft_sharepoint':  '/connector-logos/microsoft-sharepoint.svg',
  'sharepoint':            '/connector-logos/microsoft-sharepoint.svg',
  'microsoft-teams':       '/connector-logos/microsoft-teams.svg',
  'microsoftteams':        '/connector-logos/microsoft-teams.svg',
  'microsoft_teams':       '/connector-logos/microsoft-teams.svg',
  'teams':                 '/connector-logos/microsoft-teams.svg',
  'microsoft-to-do':       '/connector-logos/microsoft-to-do.svg',
  'microsofttodo':         '/connector-logos/microsoft-to-do.svg',
  'microsoft-todo':        '/connector-logos/microsoft-to-do.svg',
  'microsoft_to_do':       '/connector-logos/microsoft-to-do.svg',
  'microsoft_todo':        '/connector-logos/microsoft-to-do.svg',
  'todo':                  '/connector-logos/microsoft-to-do.svg',
  'microsoft-word':        '/connector-logos/microsoft-word.svg',
  'microsoftword':         '/connector-logos/microsoft-word.svg',
  'microsoft_word':        '/connector-logos/microsoft-word.svg',
  'word':                  '/connector-logos/microsoft-word.svg',
  'modjo':             '/connector-logos/modjo-ai.jpeg',
  'modjo-ai':          '/connector-logos/modjo-ai.jpeg',
  'monday':            '/connector-logos/monday.svg',
  'monday-com':        '/connector-logos/monday.svg',
  'mondaycom':         '/connector-logos/monday.svg',
  'monday_com':        '/connector-logos/monday.svg',
  'power-bi':          '/connector-logos/power-bi.svg',
  'powerbi':           '/connector-logos/power-bi.svg',
  'power_bi':          '/connector-logos/power-bi.svg',
  'semrush':           '/connector-logos/semrush.jpeg',
  'zigpoll':           '/connector-logos/zigpoll.jpeg',
  'slack-bot':         '/connector-logos/slack.svg',
  'slackbot':          '/connector-logos/slack.svg',
  'slack_bot':         '/connector-logos/slack.svg',
  'booking-com-reservations':  '/connector-logos/booking-com.svg',
  'bookingcomreservations':    '/connector-logos/booking-com.svg',
  'booking_com_reservations':  '/connector-logos/booking-com.svg',
  'quickbooks':                '/connector-logos/quickbooks.svg',
  'quick-books':               '/connector-logos/quickbooks.svg',
  'quick_books':               '/connector-logos/quickbooks.svg',
  'intuit-quickbooks':         '/connector-logos/quickbooks.svg',
  'intuitquickbooks':          '/connector-logos/quickbooks.svg',
  'intuit_quickbooks':         '/connector-logos/quickbooks.svg',
  'zoho-books':                '/connector-logos/zoho-books.jpeg',
  'zohobooks':                 '/connector-logos/zoho-books.jpeg',
  'zoho_books':                '/connector-logos/zoho-books.jpeg',
  'google-meet':               '/connector-logos/google-meet.svg',
  'googlemeet':                '/connector-logos/google-meet.svg',
  'google_meet':               '/connector-logos/google-meet.svg',
  'google-slides':             '/connector-logos/google-slides.svg',
  'googleslides':              '/connector-logos/google-slides.svg',
  'google_slides':             '/connector-logos/google-slides.svg',
  'richpanel':                 '/connector-logos/richpanel.jpeg',
  'rich-panel':                '/connector-logos/richpanel.jpeg',
  'rich_panel':                '/connector-logos/richpanel.jpeg',
  'twilio':                    '/connector-logos/twilio.jpeg',
}

/**
 * Resolve a connector's bundled logo from its slug or display name. Tries the
 * raw value first, then a normalized slug (lowercase, spaces→dashes, stripped
 * of punctuation) so both "hubspot" and "HubSpot" resolve. Returns null when
 * no asset is bundled for that connector — callers should render a fallback.
 */
export function connectorLogoSrc(slugOrName: string | null | undefined): string | null {
  if (!slugOrName) return null
  const raw = slugOrName.toLowerCase()
  if (CONNECTOR_LOGO_MAP[raw]) return CONNECTOR_LOGO_MAP[raw]
  const norm = raw.replace(/\s+/g, '-').replace(/[^a-z0-9-_]/g, '')
  return CONNECTOR_LOGO_MAP[norm] ?? null
}

// Canonical display names for connector slugs. Used when reconstructing
// connector context from historical tool_calls (which only carry slugs).
// Live `context` SSE events already include `display_name`; this only fills
// the gap when no name is available. Heuristic fallback (title-cased slug)
// covers everything else.
const CONNECTOR_DISPLAY_NAME: Record<string, string> = {
  'airtable':         'Airtable',
  'asana':            'Asana',
  'calendly':         'Calendly',
  'clickup':          'ClickUp',
  'fireflies':        'Fireflies',
  'gmail':            'Gmail',
  'googleads':        'Google Ads',
  'googlecalendar':   'Google Calendar',
  'googledocs':       'Google Docs',
  'googledrive':      'Google Drive',
  'googlesheets':     'Google Sheets',
  'hubspot':          'HubSpot',
  'jira':             'Jira',
  'linear':           'Linear',
  'linkedin':         'LinkedIn',
  'meta':             'Meta',
  'facebook':         'Facebook',
  'notion':           'Notion',
  'outlook':          'Outlook',
  'salesforce':       'Salesforce',
  'shipengine':       'ShipEngine',
  'shopify':          'Shopify',
  'slack':            'Slack',
  'stripe':           'Stripe',
  'zoom':             'Zoom',
  'beehiiv':          'Beehiiv',
  'booking-com':      'Booking.com',
  'bookingcom':       'Booking.com',
  'canva':            'Canva',
  'customer-io':      'Customer.io',
  'customerio':       'Customer.io',
  'customer_io':      'Customer.io',
  'databricks':       'Databricks',
  'figma':            'Figma',
  'intercom':         'Intercom',
  'miro':             'Miro',
  'mixpanel':         'Mixpanel',
  'supabase':         'Supabase',
  'triple-whale':     'Triple Whale',
  'triplewhale':      'Triple Whale',
  'triple_whale':     'Triple Whale',
  'vercel':           'Vercel',
  'whatsapp':         'WhatsApp',
  'amplitude':        'Amplitude',
  'attio':            'Attio',
  'box':              'Box',
  'fathom':           'Fathom',
  'granola':          'Granola',
  'granola-ai':        'Granola',
  'microsoft-bookings':    'Microsoft Bookings',
  'microsoftbookings':     'Microsoft Bookings',
  'microsoft_bookings':    'Microsoft Bookings',
  'bookings':              'Microsoft Bookings',
  'microsoft-clarity':     'Microsoft Clarity',
  'microsoftclarity':      'Microsoft Clarity',
  'microsoft_clarity':     'Microsoft Clarity',
  'clarity':               'Microsoft Clarity',
  'microsoft-excel':       'Microsoft Excel',
  'microsoftexcel':        'Microsoft Excel',
  'microsoft_excel':       'Microsoft Excel',
  'excel':                 'Excel',
  'microsoft-onedrive':    'Microsoft OneDrive',
  'microsoftonedrive':     'Microsoft OneDrive',
  'microsoft_onedrive':    'Microsoft OneDrive',
  'onedrive':              'OneDrive',
  'microsoft-onenote':     'Microsoft OneNote',
  'microsoftonenote':      'Microsoft OneNote',
  'microsoft_onenote':     'Microsoft OneNote',
  'onenote':               'OneNote',
  'microsoft-planner':     'Microsoft Planner',
  'microsoftplanner':      'Microsoft Planner',
  'microsoft_planner':     'Microsoft Planner',
  'planner':               'Microsoft Planner',
  'microsoft-powerpoint':  'Microsoft PowerPoint',
  'microsoftpowerpoint':   'Microsoft PowerPoint',
  'microsoft_powerpoint':  'Microsoft PowerPoint',
  'powerpoint':            'PowerPoint',
  'microsoft-sharepoint':  'Microsoft SharePoint',
  'microsoftsharepoint':   'Microsoft SharePoint',
  'microsoft_sharepoint':  'Microsoft SharePoint',
  'sharepoint':            'SharePoint',
  'microsoft-teams':       'Microsoft Teams',
  'microsoftteams':        'Microsoft Teams',
  'microsoft_teams':       'Microsoft Teams',
  'teams':                 'Microsoft Teams',
  'microsoft-to-do':       'Microsoft To Do',
  'microsofttodo':         'Microsoft To Do',
  'microsoft-todo':        'Microsoft To Do',
  'microsoft_to_do':       'Microsoft To Do',
  'microsoft_todo':        'Microsoft To Do',
  'todo':                  'Microsoft To Do',
  'microsoft-word':        'Microsoft Word',
  'microsoftword':         'Microsoft Word',
  'microsoft_word':        'Microsoft Word',
  'word':                  'Word',
  'modjo':             'Modjo',
  'modjo-ai':          'Modjo',
  'monday':            'Monday.com',
  'monday-com':        'Monday.com',
  'mondaycom':         'Monday.com',
  'monday_com':        'Monday.com',
  'power-bi':          'Power BI',
  'powerbi':           'Power BI',
  'power_bi':          'Power BI',
  'semrush':           'Semrush',
  'zigpoll':           'Zigpoll',
  'slack-bot':         'Slack',
  'slackbot':          'Slack',
  'slack_bot':         'Slack',
  'booking-com-reservations': 'Booking.com Reservations',
  'bookingcomreservations':   'Booking.com Reservations',
  'booking_com_reservations': 'Booking.com Reservations',
  'quickbooks':               'QuickBooks',
  'quick-books':              'QuickBooks',
  'quick_books':              'QuickBooks',
  'intuit-quickbooks':        'QuickBooks',
  'intuitquickbooks':         'QuickBooks',
  'intuit_quickbooks':        'QuickBooks',
  'zoho-books':               'Zoho Books',
  'zohobooks':                'Zoho Books',
  'zoho_books':               'Zoho Books',
  'google-meet':              'Google Meet',
  'googlemeet':               'Google Meet',
  'google_meet':              'Google Meet',
  'google-slides':            'Google Slides',
  'googleslides':             'Google Slides',
  'google_slides':            'Google Slides',
  'richpanel':                'Richpanel',
  'rich-panel':               'Richpanel',
  'rich_panel':               'Richpanel',
  'twilio':                   'Twilio',
}

export function connectorDisplayName(slug: string | null | undefined): string {
  if (!slug) return ''
  const s = slug.toLowerCase()
  return CONNECTOR_DISPLAY_NAME[s]
    ?? slug.replace(/[_-]+/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
}
