// Canonical display names for connector slugs. Used when reconstructing
// connector context from historical tool_calls (which only carry slugs).
// Live `context` SSE events already include `display_name`; this only fills
// the gap when no name is available. Heuristic fallback (title-cased slug)
// covers everything else.
//
// Logos are NOT resolved here — every connector image comes from the backend's
// logo_url/icon_url (see toConnector in @/lib/connector). There are no bundled
// brand assets to fall back to.
const CONNECTOR_DISPLAY_NAME: Record<string, string> = {
  'airtable':         'Airtable',
  'asana':            'Asana',
  'calendly':         'Calendly',
  'clickup':          'ClickUp',
  'fireflies':        'Fireflies',
  'gmail':            'Gmail',
  'googleads':        'Google Ads',
  'googlecalendar':   'Google Calendar',
  'googledocs':       'Google Docs',
  'googledrive':      'Google Drive',
  'googlesheets':     'Google Sheets',
  'hubspot':          'HubSpot',
  'jira':             'Jira',
  'linear':           'Linear',
  'linkedin':         'LinkedIn',
  'meta':             'Meta',
  'facebook':         'Facebook',
  'notion':           'Notion',
  'outlook':          'Outlook',
  'salesforce':       'Salesforce',
  'shipengine':       'ShipEngine',
  'shopify':          'Shopify',
  'slack':            'Slack',
  'stripe':           'Stripe',
  'zoom':             'Zoom',
  'beehiiv':          'Beehiiv',
  'booking-com':      'Booking.com',
  'bookingcom':       'Booking.com',
  'canva':            'Canva',
  'customer-io':      'Customer.io',
  'customerio':       'Customer.io',
  'customer_io':      'Customer.io',
  'databricks':       'Databricks',
  'figma':            'Figma',
  'intercom':         'Intercom',
  'miro':             'Miro',
  'mixpanel':         'Mixpanel',
  'supabase':         'Supabase',
  'triple-whale':     'Triple Whale',
  'triplewhale':      'Triple Whale',
  'triple_whale':     'Triple Whale',
  'vercel':           'Vercel',
  'whatsapp':         'WhatsApp',
  'amplitude':        'Amplitude',
  'apollo':           'Apollo',
  'apollo-io':        'Apollo',
  'apolloio':         'Apollo',
  'apollo_io':        'Apollo',
  'attio':            'Attio',
  'box':              'Box',
  'fathom':           'Fathom',
  'granola':          'Granola',
  'granola-ai':        'Granola',
  'microsoft-bookings':    'Microsoft Bookings',
  'microsoftbookings':     'Microsoft Bookings',
  'microsoft_bookings':    'Microsoft Bookings',
  'bookings':              'Microsoft Bookings',
  'microsoft-clarity':     'Microsoft Clarity',
  'microsoftclarity':      'Microsoft Clarity',
  'microsoft_clarity':     'Microsoft Clarity',
  'clarity':               'Microsoft Clarity',
  'microsoft-excel':       'Microsoft Excel',
  'microsoftexcel':        'Microsoft Excel',
  'microsoft_excel':       'Microsoft Excel',
  'excel':                 'Excel',
  'microsoft-onedrive':    'Microsoft OneDrive',
  'microsoftonedrive':     'Microsoft OneDrive',
  'microsoft_onedrive':    'Microsoft OneDrive',
  'onedrive':              'OneDrive',
  'microsoft-onenote':     'Microsoft OneNote',
  'microsoftonenote':      'Microsoft OneNote',
  'microsoft_onenote':     'Microsoft OneNote',
  'onenote':               'OneNote',
  'microsoft-planner':     'Microsoft Planner',
  'microsoftplanner':      'Microsoft Planner',
  'microsoft_planner':     'Microsoft Planner',
  'planner':               'Microsoft Planner',
  'microsoft-powerpoint':  'Microsoft PowerPoint',
  'microsoftpowerpoint':   'Microsoft PowerPoint',
  'microsoft_powerpoint':  'Microsoft PowerPoint',
  'powerpoint':            'PowerPoint',
  'microsoft-sharepoint':  'Microsoft SharePoint',
  'microsoftsharepoint':   'Microsoft SharePoint',
  'microsoft_sharepoint':  'Microsoft SharePoint',
  'sharepoint':            'SharePoint',
  'microsoft-teams':       'Microsoft Teams',
  'microsoftteams':        'Microsoft Teams',
  'microsoft_teams':       'Microsoft Teams',
  'teams':                 'Microsoft Teams',
  'microsoft-to-do':       'Microsoft To Do',
  'microsofttodo':         'Microsoft To Do',
  'microsoft-todo':        'Microsoft To Do',
  'microsoft_to_do':       'Microsoft To Do',
  'microsoft_todo':        'Microsoft To Do',
  'todo':                  'Microsoft To Do',
  'microsoft-word':        'Microsoft Word',
  'microsoftword':         'Microsoft Word',
  'microsoft_word':        'Microsoft Word',
  'word':                  'Word',
  'modjo':             'Modjo',
  'modjo-ai':          'Modjo',
  'monday':            'Monday.com',
  'monday-com':        'Monday.com',
  'mondaycom':         'Monday.com',
  'monday_com':        'Monday.com',
  'power-bi':          'Power BI',
  'powerbi':           'Power BI',
  'power_bi':          'Power BI',
  'semrush':           'Semrush',
  'zigpoll':           'Zigpoll',
  'slack-bot':         'Slack',
  'slackbot':          'Slack',
  'slack_bot':         'Slack',
  'booking-com-reservations': 'Booking.com Reservations',
  'bookingcomreservations':   'Booking.com Reservations',
  'booking_com_reservations': 'Booking.com Reservations',
  'quickbooks':               'QuickBooks',
  'quick-books':              'QuickBooks',
  'quick_books':              'QuickBooks',
  'intuit-quickbooks':        'QuickBooks',
  'intuitquickbooks':         'QuickBooks',
  'intuit_quickbooks':        'QuickBooks',
  'zoho-books':               'Zoho Books',
  'zohobooks':                'Zoho Books',
  'zoho_books':               'Zoho Books',
  'google-meet':              'Google Meet',
  'googlemeet':               'Google Meet',
  'google_meet':              'Google Meet',
  'google-slides':            'Google Slides',
  'googleslides':             'Google Slides',
  'google_slides':            'Google Slides',
  'richpanel':                'Richpanel',
  'rich-panel':               'Richpanel',
  'rich_panel':               'Richpanel',
  'twilio':                   'Twilio',
  'bigcommerce':              'BigCommerce',
  'google_forms':             'Google Forms',
  'google-forms':             'Google Forms',
  'googleforms':              'Google Forms',
  'granola_mcp':              'Granola',
  'heatmap':                  'Heatmap',
  'instantly':                'Instantly',
  'instantly-ai':             'Instantly',
  'instantlyai':              'Instantly',
  'instantly_ai':             'Instantly',
  'one_drive':                'OneDrive',
  'microsoft_power_bi':       'Power BI',
  'resend':                   'Resend',
  'shipstation-v2':           'ShipStation',
  'shipstation_v2':           'ShipStation',
}

export function connectorDisplayName(slug: string | null | undefined): string {
  if (!slug) return ''
  const s = slug.toLowerCase()
  return CONNECTOR_DISPLAY_NAME[s]
    ?? slug.replace(/[_-]+/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
}
