import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// Heavy packages must be loaded through their wrappers so they stay out of the initial bundle
// (see docs/perf/README.md). A dynamic `import("pkg")` is always allowed; only static imports are
// restricted. Tests may import them directly.
const llmIcons = {
  name: "@strange-huge/icons/llm",
  message:
    "This package is ~10 MB as one module. Use ThemedLlmIcon / '@/lib/llm-icons.generated' (add a provider in scripts/generate-llm-icons.mjs).",
};
const mermaid = {
  name: "beautiful-mermaid",
  allowTypeImports: true,
  message: "Bundles a ~1.4 MB layout engine. Load it with `await import('beautiful-mermaid')` (see MermaidDiagram).",
};
const mixpanel = {
  name: "mixpanel-browser",
  allowTypeImports: true,
  message: "Load the SDK only through src/lib/analytics/mixpanel.ts, which imports it dynamically.",
};
const recharts = {
  name: "recharts",
  allowTypeImports: true,
  message: "Recharts is ~290 KB. Import it only inside a lazily loaded chart component (see components/Sparkline).",
};

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/generate-llm-icons.mjs
    "src/lib/llm-icons.generated.ts",
  ]),
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/**/*.test.{ts,tsx}"],
    rules: {
      "no-restricted-imports": ["error", { paths: [llmIcons, mermaid, mixpanel, recharts] }],
    },
  },
  // The chart components that own Recharts. SparklineChart is loaded lazily by components/Sparkline;
  // UsageBarChart is only used by the admin analytics route.
  {
    files: ["src/components/Sparkline/SparklineChart.tsx", "src/components/UsageBarChart/index.tsx"],
    rules: {
      "no-restricted-imports": ["error", { paths: [llmIcons, mermaid, mixpanel] }],
    },
  },
]);

export default eslintConfig;
