openapi: 3.1.0
info:
  title: FastAPI - LLM
  version: 0.1.0
paths:
  /llm/models:
    get:
      tags:
      - llm
      summary: List Models
      operationId: list_models_llm_models_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GetModels'
                type: array
                title: Response List Models Llm Models Get
      security:
      - HTTPBearer: []
  /llm/models/all:
    get:
      tags:
      - llm
      summary: List All Models
      operationId: list_all_models_llm_models_all_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GetModelsWithStatus'
                type: array
                title: Response List All Models Llm Models All Get
      security:
      - HTTPBearer: []
  /llm/models/block:
    patch:
      tags:
      - llm
      summary: Block Model
      operationId: block_model_llm_models_block_patch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlockModel'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /llm/models/test:
    post:
      tags:
      - llm
      summary: Test Models
      operationId: test_models_llm_models_test_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestModelRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
components:
  schemas:
    BlockModel:
      properties:
        model_id:
          type: string
          format: uuid
          title: Model Id
      type: object
      required:
      - model_id
      title: BlockModel
    GetModels:
      properties:
        model_id:
          type: string
          format: uuid
          title: Model Id
        model_name:
          type: string
          title: Model Name
        model_provider:
          type: string
          title: Model Provider
        model_inputs:
          items:
            type: string
          type: array
          title: Model Inputs
        model_outputs:
          items:
            type: string
          type: array
          title: Model Outputs
        model_context_window:
          anyOf:
          - type: integer
          - type: 'null'
          title: Model Context Window
        model_output_size:
          anyOf:
          - type: integer
          - type: 'null'
          title: Model Output Size
        model_input_cost:
          anyOf:
          - type: number
          - type: 'null'
          title: Model Input Cost
        model_output_cost:
          anyOf:
          - type: number
          - type: 'null'
          title: Model Output Cost
        model_plan_type:
          type: string
          title: Model Plan Type
        model_description:
          type: string
          title: Model Description
      type: object
      required:
      - model_id
      - model_name
      - model_provider
      - model_inputs
      - model_outputs
      - model_plan_type
      - model_description
      title: GetModels
    GetModelsWithStatus:
      properties:
        model_id:
          type: string
          format: uuid
          title: Model Id
        model_name:
          type: string
          title: Model Name
        model_provider:
          type: string
          title: Model Provider
        model_inputs:
          items:
            type: string
          type: array
          title: Model Inputs
        model_outputs:
          items:
            type: string
          type: array
          title: Model Outputs
        model_context_window:
          anyOf:
          - type: integer
          - type: 'null'
          title: Model Context Window
        model_output_size:
          anyOf:
          - type: integer
          - type: 'null'
          title: Model Output Size
        model_input_cost:
          anyOf:
          - type: number
          - type: 'null'
          title: Model Input Cost
        model_output_cost:
          anyOf:
          - type: number
          - type: 'null'
          title: Model Output Cost
        model_plan_type:
          type: string
          title: Model Plan Type
        model_description:
          type: string
          title: Model Description
        blocked:
          type: boolean
          title: Blocked
      type: object
      required:
      - model_id
      - model_name
      - model_provider
      - model_inputs
      - model_outputs
      - model_plan_type
      - model_description
      - blocked
      title: GetModelsWithStatus
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    TestModelRequest:
      properties:
        model_ids:
          items:
            type: string
            format: uuid
          type: array
          maxItems: 3
          minItems: 1
          title: Model Ids
        prompt:
          type: string
          title: Prompt
      type: object
      required:
      - model_ids
      - prompt
      title: TestModelRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
