import type { ReasoningSection, ReasoningTimelineItem } from "@/lib/reasoning";
import type { ConnectorPermissionPrompt, ChatPrompt } from '@/lib/api/prompts'
export type {
  ConnectorPermissionPrompt,
  ChatPrompt,
  ChatPromptOption,
  ChatPromptQuestion,
} from '@/lib/api/prompts'

export interface Chat {
  id: string;
  owner_user_id?: string;
  can_edit?: boolean;
  visibility?: "private" | "team" | "archived";
  team_id?: string | null;
  title: string;
  created_at: string;
  updated_at: string;
  starred: boolean;
  model?: string;
  message_count?: number;
  pins_count?: number;
  last_message_at?: string;
  project_id?: string | null;
}

export interface Attachment {
  id: string;
  file_name: string;
  file_type: string;
  file_size: number;
  url?: string;
  thumbnail_url?: string;
  /** True while the file is being sent to the backend (real XHR upload in progress). */
  uploading?: boolean;
  /** 0–100 upload progress as reported by XHR. Only meaningful when uploading is true. */
  uploadProgress?: number;
}

export interface Citation {
  index: number;
  source_id: string;
  text: string;
}

export interface Source {
  id: string;
  url: string;
  title: string;
  favicon?: string;
}

/** A file attachment returned by the backend on messages (uploaded or generated). */
export interface BackendFileAttachment {
  file_link?: string;
  url?: string;
  link?: string;
  mime_type?: string;
  origin?: "uploaded" | "generated" | string | null;
  file_name?: string;
  name?: string;
}

export interface Message {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  created_at: string;
  chat_id: string;
  model?: string;
  /** Model name string as returned by the backend (e.g. "GPT-5 nano"). */
  model_name?: string;
  attachments?: Attachment[];
  /** Raw file_attachments from the backend (uploaded + generated files). */
  file_attachments?: BackendFileAttachment[];
  thinking?: string;
  /** Structured reasoning steps from the backend (heading + body per step). */
  reasoning_sections?: ReasoningSection[];
  citations?: Citation[];
  sources?: Source[];
  /** Raw web_searches payload from the backend - used to hydrate sources on load. */
  web_searches?: Array<{ query: string; links: string[]; results?: Array<Record<string, unknown>> }>;
  /** Image URLs generated by the assistant (from the image_links backend field). */
  image_links?: string[];
}

// ── Connector SSE prompt payloads ─────────────────────────────────────────────

/** Emitted when the LLM tries to use a connector that is not yet linked. */
export interface ConnectorConnectPrompt {
  /** Unique request ID from the backend (for deduplication). */
  request_id:      string
  /** Slug, name and logo as one resolved identity — built with `toConnector`
   *  from the raw event so no call site re-derives them. */
  connector:       import('@/lib/connector').Connector
  auth_mode:       'oauth2' | 'api_key'
  provider?:       'pipedream' | 'mcp' | 'zapier'
  /** The action that needs the app. Empty when the run is binding the app
   *  itself rather than calling one operation. */
  tool_name:       string
  /** Structured credential fields for api_key connectors, as returned by GET /connectors/{slug}. */
  api_key_fields?: import('@/lib/api/connectors').ApiKeyField[]
}

export interface ExternalOutputAction {
  verb: string
  target: string
  connector: string
  connector_slug?: string | null
  logo_url?: string | null
  detail?: string | null
  view_url?: string | null
}

/** Extends the API Message with transient streaming-only UI state. */
export interface UIMessage extends Message {
  /** True while the assistant is generating a response for this message. */
  isLoading?: boolean
  /** True while a <think> block is still open (streaming). */
  isThinkingInProgress?: boolean
  /** True when the user clicked Stop during generation. */
  stoppedByUser?: boolean
  /** True when `content` is a friendly error message rather than an actual
   *  model response — renders with a distinct error treatment instead of a
   *  normal assistant bubble. */
  isError?: boolean
  /** Model name reported by backend during streaming. */
  modelName?: string
  /** Model metadata selected for this response. */
  modelMeta?: ModelSelectedMeta
  /** Activities performed during response generation (tool uses, web search, etc.) */
  activities?: ActivityItem[]
  /** Arrival-ordered reasoning/tool trace for the active stream. Persisted
   * messages fall back to reasoning_sections + activities. */
  reasoningTimeline?: ReasoningTimelineItem[]
  /** Generated images (inline from LLM or named event). */
  images?: GeneratedImage[]
  /** Generated files (documents, CSVs, etc.). */
  generatedFiles?: GeneratedFile[]
  /** Structured response blocks (table, chart, code, callout, etc.). */
  responseBlocks?: ResponseBlock[]
  /** Web citation sources for inline {1} {2} chips in response text. */
  webCitations?: WebCitation[]
  /** Connector "connect" prompts emitted mid-stream when a tool needs linking. */
  connectorConnectPrompts?: ConnectorConnectPrompt[]
  /** Connector "permission" prompts emitted mid-stream when a tool policy is "ask". */
  connectorPermissionPrompts?: ConnectorPermissionPrompt[]
  /** Non-connector prompt-gate cards: clarifications, choices, and approvals. */
  chatPrompts?: ChatPrompt[]
  /** Confirmed external writes performed during this turn. */
  externalOutputActions?: ExternalOutputAction[]
  /** @-mentioned pins attached to this user message (optimistic; not persisted across refresh). */
  mentionedPins?: Array<{ id: string; label: string }>
  /** Stable React list key, set once at creation and never reassigned.
   *  `id` itself gets swapped in place from a temp "loading-assistant-…"/
   *  "optimistic-…" value to the real backend UUID once the backend confirms
   *  the message (see use-streaming-chat.ts's `message_saved` handling) — if
   *  the message list were keyed directly by `id`, that swap would look like
   *  a brand-new row to React and remount it, replaying its entrance
   *  animation on content that's already fully visible. Keying by this field
   *  instead keeps the row's identity stable across that swap. */
  reactKey?: string
}

/** Model selection metadata from the backend. */
export interface ModelSelectedMeta {
  modelId: string
  modelName: string
  deploymentName?: string
  company?: string
  complexity?: string
  thinkingEnabled?: boolean
  effort?: string
}

/** Activity types matching backend tool names. */
export type ActivityType =
  | 'web-search'
  | 'browser'
  | 'read-pages'
  | 'csv-execute'
  | 'fetch-resource'
  | 'tool-call'
  | 'doc-execute'
  | 'docx-progress'
  | 'skills'
  | 'other'

/** Status values for tool progress. `stopped` marks an activity that was
 *  still in-flight when the user hit Stop (or the tab reloaded mid-stream) —
 *  distinct from `error` since the tool wasn't refused or failed, it was
 *  just never allowed to finish. */
export type ActivityStatus = 'start' | 'executing' | 'reading' | 'done' | 'error' | 'stopped'

/** A single activity (tool use) performed by the AI during response generation. */
export interface ActivityItem {
  /** Unique ID for this activity (tool_call_id or generated). */
  id: string
  /** Type of activity. */
  type: ActivityType
  /** Tool name as reported by backend. */
  toolName?: string
  /** Human-readable detail text. */
  detail?: string
  /** Current status. */
  status: ActivityStatus
  /** Search results or links. */
  results?: { title: string; url?: string; domain?: string }[]
  /** Duration in seconds (from tool_complete). */
  durationS?: number
  /** Progress message from tool_progress. */
  progressMessage?: string
  /** Completion percentage from tool_progress, 0-100. */
  percent?: number
  /** Code preview from tool_progress (csv_execute, docx). */
  codePreview?: string
  /** Filename associated with the tool (read_pages, csv, docx). */
  filename?: string
  /** Human-readable label from backend (e.g. "Generating PDF", "Searching the web"). */
  label?: string
}

/** An image generated during the response. */
export interface GeneratedImage {
  url: string
  s3Key?: string
}

/** A file generated during the response. */
export interface GeneratedFile {
  url: string
  s3Key?: string
  filename: string
  mimeType?: string
}

// ── Structured output types (response blocks) ─────────────────────────────────

/** A web citation source for inline {1}{2} reference chips (distinct from Message.citations). */
export interface WebCitation {
  title: string
  url?: string
  domain?: string
}

export interface TableBadgeStyle { label: string; color: string; bg: string; border?: string }

export type TableCellValue =
  | string
  | number
  | { type: 'badge';  label: string; color: string; bg: string; border?: string }
  | { type: 'check';  value: boolean }
  | { type: 'rich';   text: string; sub?: string; badge?: TableBadgeStyle }

export interface TableData {
  caption?: string
  headers: string[]
  rows: TableCellValue[][]
  variant?: 'basic' | 'striped' | 'compact' | 'badges' | 'financial' | 'hoverable' | 'minimal' | 'feature-comparison' | 'mixed-content'
  sortable?: boolean
  totalsRow?: boolean
  accentRows?: number[]
  badgeMap?: Record<string, { color: string; bg: string; border?: string }>
}

export interface BarChartData {
  title?: string
  unit?: string
  bars: { label: string; value: number; color?: string }[]
  maxValue?: number
  variant?: 'vertical' | 'horizontal' | 'grouped' | 'stacked' | 'stacked-100' | 'positive-negative'
  datasets?: { label: string; color?: string; values: number[] }[]
  labels?: string[]
}

export interface StepsData {
  title?: string
  steps: { label: string; description?: string }[]
}

export interface CodeData {
  language: string
  code: string
  caption?: string
}

export interface CalloutData {
  variant: 'info' | 'warning' | 'success' | 'error' | 'tip'
  title?: string
  body: string
}

export interface TagsData {
  title?: string
  tags: { label: string; color?: string }[]
}

export interface FollowUpsData {
  prompts: string[]
}

export interface PieChartData {
  title?: string
  unit?: string
  centerLabel?: string
  segments: { label: string; value: number; color?: string }[]
}

export interface LineChartData {
  title?: string
  unit?: string
  xLabel?: string
  yLabel?: string
  lines: { label: string; color?: string; points: { x: string; y: number }[] }[]
}

export interface CardData {
  title?: string
  subtitle?: string
  body: string
  badge?: string
  badgeColor?: string
}

export interface ConnectorErrorData {
  connector: string
  icon?: string
  message: string
  cta: string
}

export interface SearchTimeoutData {
  query: string
  message: string
  cta: string
}

/** Discriminated union of all structured response block types. */
export type ResponseBlock =
  | { kind: 'text';            content: string; webCitations?: WebCitation[] }
  | { kind: 'table';           data: TableData }
  | { kind: 'bar-chart';       data: BarChartData }
  | { kind: 'steps';           data: StepsData }
  | { kind: 'code';            data: CodeData }
  | { kind: 'callout';         data: CalloutData }
  | { kind: 'tags';            data: TagsData }
  | { kind: 'follow-ups';      data: FollowUpsData }
  | { kind: 'pie-chart';       data: PieChartData }
  | { kind: 'line-chart';      data: LineChartData }
  | { kind: 'card';            data: CardData }
  | { kind: 'connector-error'; data: ConnectorErrorData }
  | { kind: 'search-timeout';  data: SearchTimeoutData }

export interface ChatsListResponse {
  chats: Chat[];
  next_cursor?: string | null;
  has_more: boolean;
  total?: number;
}

export interface MessagesListResponse {
  messages: Message[];
  next_cursor?: string | null;
  has_more: boolean;
}
