export interface Chat {
  id: string;
  owner_user_id?: string;
  can_edit?: boolean;
  visibility?: "private" | "team";
  team_id?: string | null;
  title: string;
  created_at: string;
  updated_at: string;
  starred: boolean;
  model?: string;
  message_count?: number;
  pins_count?: number;
  last_message_at?: string;
  project_id?: string | null;
}

export interface Attachment {
  id: string;
  file_name: string;
  file_type: string;
  file_size: number;
  url?: string;
  thumbnail_url?: string;
  /** True while the file is being sent to the backend (real XHR upload in progress). */
  uploading?: boolean;
  /** 0–100 upload progress as reported by XHR. Only meaningful when uploading is true. */
  uploadProgress?: number;
}

export interface Citation {
  index: number;
  source_id: string;
  text: string;
}

export interface Source {
  id: string;
  url: string;
  title: string;
  favicon?: string;
}

/** A file attachment returned by the backend on messages (uploaded or generated). */
export interface BackendFileAttachment {
  file_link?: string;
  url?: string;
  link?: string;
  mime_type?: string;
  origin?: "uploaded" | "generated" | string | null;
  file_name?: string;
  name?: string;
}

export interface Message {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  created_at: string;
  chat_id: string;
  model?: string;
  /** Model name string as returned by the backend (e.g. "GPT-5 nano"). */
  model_name?: string;
  attachments?: Attachment[];
  /** Raw file_attachments from the backend (uploaded + generated files). */
  file_attachments?: BackendFileAttachment[];
  thinking?: string;
  /** Structured reasoning steps from the backend (heading + body per step). */
  reasoning_sections?: Array<{ heading: string; body: string }>;
  citations?: Citation[];
  sources?: Source[];
  /** Raw web_searches payload from the backend - used to hydrate sources on load. */
  web_searches?: Array<{ query: string; links: string[] }>;
  /** Image URLs generated by the assistant (from the image_links backend field). */
  image_links?: string[];
  /** Structured response blocks (table, chart, steps, etc.) persisted by the backend. */
  response_blocks?: Array<{ kind: string; [key: string]: unknown }>;
}

export interface ChatsListResponse {
  chats: Chat[];
  next_cursor?: string | null;
  has_more: boolean;
  total?: number;
}

export interface MessagesListResponse {
  messages: Message[];
  next_cursor?: string | null;
  has_more: boolean;
}
