#!/usr/bin/env node
import { SecretsManagerClient, GetSecretValueCommand } from "@aws-sdk/client-secrets-manager";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const BOOTSTRAP = resolve(ROOT, ".env.local");
const OUT = resolve(ROOT, ".env.development.local");

function parseDotenv(path) {
  const out = {};
  if (!existsSync(path)) return out;
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (!m) continue;
    out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

const boot = parseDotenv(BOOTSTRAP);
const region = boot.AWS_REGION || process.env.AWS_REGION || "us-east-1";
const secretName = boot.AWS_SECRET_NAME || process.env.AWS_SECRET_NAME;
const accessKeyId = boot.AWS_ACCESS_KEY_ID || process.env.AWS_ACCESS_KEY_ID;
const secretAccessKey = boot.AWS_SECRET_ACCESS_KEY || process.env.AWS_SECRET_ACCESS_KEY;

if (!secretName || !accessKeyId || !secretAccessKey) {
  console.error("[load-secrets] missing AWS bootstrap (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / AWS_SECRET_NAME) in .env.local");
  process.exit(1);
}

const client = new SecretsManagerClient({ region, credentials: { accessKeyId, secretAccessKey } });
const res = await client.send(new GetSecretValueCommand({ SecretId: secretName }));
const values = JSON.parse(res.SecretString);

const lines = [
  "# Auto-generated by scripts/load-secrets.mjs — do not edit by hand",
  `# Source: AWS Secrets Manager / ${secretName}`,
  `# Generated: ${new Date().toISOString()}`,
  "",
];
for (const [k, v] of Object.entries(values)) lines.push(`${k}=${v ?? ""}`);

writeFileSync(OUT, lines.join("\n") + "\n", { mode: 0o600 });
console.log(`[load-secrets] wrote ${Object.keys(values).length} keys from ${secretName} → ${OUT}`);
